trigger: none 
pool: Dec22agent
stages:
  - stage: 
    displayName: terraform_tool
    jobs:
      - job: 
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@5
          displayName: init
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'Dec_2225'
            backendAzureRmResourceGroupName: 'Ashish9rg'
            backendAzureRmStorageAccountName: 'ashishstorage24dec'
            backendAzureRmContainerName: 'ashish1con'
            backendAzureRmKey: 'ashishkkey.tfstate'
        - task: TerraformTask@5
          displayName: plan
          inputs:
            provider: 'azurerm'
            command: 'plan'
            environmentServiceNameAzureRM: 'Dec_2225'
      
    